import { groth16 } from "snarkjs";
import { readFileSync } from "node:fs";
import { BASE_FEE, Contract, Keypair, TransactionBuilder, nativeToScVal, scValToNative } from "@stellar/stellar-sdk";
import { Server } from "@stellar/stellar-sdk/rpc";
const VERIFIER="CDBACVTNIBBEP5AOMIR22PAFJMWVLV75UYXRM4BPCSHG6EHHMGWIRDQC", PASS="Test SDF Network ; September 2015", B="/Users/pp/Documents/Projects/soracle/packages/circuits";
const secret = readFileSync(0,"utf8").trim();
const fe=(d)=>{let h=BigInt(d).toString(16);h=h.padStart(64,"0");const o=new Uint8Array(32);for(let i=0;i<32;i++)o[i]=parseInt(h.slice(i*2,i*2+2),16);return o;};
const cat=(...a)=>{const n=a.reduce((s,x)=>s+x.length,0);const o=new Uint8Array(n);let k=0;for(const x of a){o.set(x,k);k+=x.length}return o;};
const g1=(p)=>cat(fe(p[0]),fe(p[1])),g2=(p)=>cat(fe(p[0][1]),fe(p[0][0]),fe(p[1][1]),fe(p[1][0]));
const input=JSON.parse(readFileSync(`${B}/test/inputs/consensus.input.json`,"utf8"));
console.log("proving…");
const {proof,publicSignals}=await groth16.fullProve(input,`${B}/build/consensus_js/consensus.wasm`,`${B}/build/consensus.zkey`);
const server=new Server("https://soroban-testnet.stellar.org");
const kp=Keypair.fromSecret(secret);
const acct=await server.getAccount(kp.publicKey());
const proofSc=nativeToScVal({a:g1(proof.pi_a),b:g2(proof.pi_b),c:g1(proof.pi_c)},{type:{a:["symbol","bytes"],b:["symbol","bytes"],c:["symbol","bytes"]}});
console.log("preparing tx…");
let tx=new TransactionBuilder(acct,{fee:BASE_FEE,networkPassphrase:PASS}).addOperation(new Contract(VERIFIER).call("verify",nativeToScVal(1,{type:"u32"}),proofSc,nativeToScVal(publicSignals.map(fe)))).setTimeout(120).build();
tx=await server.prepareTransaction(tx); tx.sign(kp);
const sent=await server.sendTransaction(tx);
console.log("sent:",sent.status,sent.hash);
const r=await server.pollTransaction(sent.hash,{attempts:30,sleepStrategy:()=>1500});
console.log("final:",r.status,"| verify returned:",r.returnValue?scValToNative(r.returnValue):null);
console.log("EXPLORER https://stellar.expert/explorer/testnet/tx/"+sent.hash);
